language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
script:
- python -m flake8 --ignore=F401,E501 --max-line-length=88
- python -m coverage run manage.py test

after_success: coveralls
deploy:
  provider: elasticbeanstalk
  access_key_id: "mZz1AG33ng4xTYqoiGI5jh3q94NqsPSBMxklVOpORughU60ofvAsV7lHqRxrhlMvUzZ6eWPQwHerXrHgZbaxGOl0MMe+902WbSOB1uZCWHquizDToU2JuetHdMHvkYHnPm9xV8dMNYRPzkcz3WevW3W9XClUPznakNokxtMNmRJAMindu3r13w2+u3kMi7F2GF9hOHvkY2jnsq92kCgQUyb751TLt0PWFgVSSOYbtAhNV0S+cfB2cIvdP7csN0kMIrt4leJpgRm8OFQQ36hlcATO1zGH31AnnBDy5KOLZ7f7aR3f1nxEwJNo2S+VXV410mO68sKyv/rFDCUNKrp1p3YVwstDwpGYilxJ8WwyGtzdbyaThkFO+woubKWDB1DPuaKtagihDkmpkoKlKBf1Cy3fGXI575k/Z3p8H2lBQnS2gNTgBervBzXtiGFB9cFtgDAevnipJHuwp5HucNA/1iGjOjiFrylwlsZ5BSrA4QVgHK0LdeOt58OJbsdW/RqjoVi9tS4yUiphVDygO0nj8y6pbaA4w2XH/Al6uQRqDmP2T5YGfHQ2jZ0zGs7YKwy8CpHD31QzK7+xlwzDvg7BFGFDS4WZEFXPVOUqomIjAQuVRGJE0IdG76FYPu2bUAQ8AO3puZnHA0DkAbfpMCrMRt3UoAyxS9n2LilWMWqKCQY="
  secret_access_key: "DOmQ5nvauaTWOb3Eeo9aYF8PZi0aycpK7Fnk6qdPdWao9X/ado5vmd6NPc3S7PrekHHsNlYEI3nxqxHuK9P6w6bXZeCpr3Dg3wHmNnZw0TytSciEEdAqBzd5ba8KGJRP0M2BdOWb17jwYoavYOVNHsO4Jde4ST6gw8YfgMMHKxQs5zXl/S4eYLJ2PcGUbqyX+AlkqVA2H59UAn6d1CG8lc3P1bpR0TiHBcHHVeraEllvaslIuUnJTAz/V5jo9nSvPBjRmfKan/lW5sf+S7LnBG+zPn1JT7Dhmh76wh0BLDdDh4EHhHZe6ttbFAsNuh7OWQHB9XdDYBKAAV57RGiK5CNoVA2IG4LYBCdhJTrClpD9aguFBC9e4lCtHEgUef/1xGnHuxgSNrClhDKIvkfbArjKe+E89O+VUWnkSe2kN/bMx2Cgm0sqFAIqjz9d8Z56BiCE9CPnZgVVim81etmQzPjZjp1rkJQ1y9zLijNRxriiKBxfF2ZlXwEvRvGfMdgDtov88GvfH/Erweppc5u/AtXLFvQ5djuGsawcAH3VTchMc+qCxnBxH0YUktvanUvqLcJMmuqL5Gh4HQwUuE4ExrvIEpr/y1HEywU6K+FXMa65afvp8X44c6QAE54R7lgmQrVordDmInsw8xg5qhO9ZqQMFprriDLG5vXi47L73TU=" 
  region: us-east-1
  app: ebdjango
  env: django-env
  bucket_name: elasticbeanstalk-us-east-1-662781481898
  on:
    all_branches: true
